### ISSUE TITLE
can i reprint the lost cards or what ?

### ISSUE THREAD

**Issue by abdotyson** [edabg/jsprintsetup#16]
I make print order but some of the codes of the  card i print was deleted i have lost a lot of money because of that any help ?
one site it's print the whole thing but other one half of the code is missing what do you think  is it ?

**Comment by mitkola** [comment]
I suppose that the reason of the problem is asynchronous behavior of print method.
If you call print method in loop you must wait to complete print of current job before do next print.
You can read more about synchronization at this [thread](https://www.mozdev.org/bugs/show_bug.cgi?id=24359).
