### ISSUE TITLE
Issue with using printWindow

### ISSUE THREAD

**Issue by jlholzbach** [edabg/jsprintsetup#17]
I am trying to implement the use of this add on into some code on I was working on where depending on what is being printed it needs to use a different printer, but not use the print dialog.  That part is working fine, but why when i try and use the printWindow method it is giving me this error.  NS_ERROR_XPC_BAD_CONVERT_JS: Could not convert JavaScript argument arg 0 [jsPrintSetup.printWindow].  I am trying to print the content of the div with the id print. Below is the code I am using to do the actual printing.  

jsPrintSetup.setSilentPrint(true);
jsPrintSetup.setPrinter(printerName);
jsPrintSetup.printWindow($("#print").html());
jsPrintSetup.setSilentPrint(false);

**Comment by mitkola** [comment]
The parameter of printWindow must be window object (not a div).
Particular can be frame or iframe.
One solution can be to [convert div to iframe](http://stackoverflow.com/questions/9434569/replace-div-with-iframe-in-javascript).
