### ISSUE TITLE
Sets Printer setings but wont print.

### ISSUE THREAD

**Issue by TomatoJoe** [edabg/jsprintsetup#2]
Hi, Ive a html page that prints labels to a DYMO LabelWriter 450
Using PaleMoon Mozillla Version: 25.7.3 on Windows 7 and Linux Mint 17.2
The printer is installed and works otherwise.

Silent printing is off at this stage as I do want the print window to popup.
jsPrintSetup sets the printer and orientation ok it seems, however,  jsPrintSetup.print();  throws DEBUG report below and the page does not print.
The window pops up, but the settings are not available and the page does not print.

DEBUG report is:
Error:
message:Component returned failure code: 0x80480007 (NS_ERROR_GFX_PRINTER_DOC_IS_BUSY) [nsIWebBrowserPrint.print]
result:2152202247
name:NS_ERROR_GFX_PRINTER_DOC_IS_BUSY
filename:jar:file:///C:/Users/[username]/AppData/Roaming/Moonchild%20Productions/Pale%20Moon/Profiles/xx4f1xoz.default/extensions/jsprintsetup@edabg.com.xpi!/components/jsPrintSetup.js
lineNumber:1502
columnNumber:0
location:JS frame :: jar:file:///C:/Users/[username]/AppData/Roaming/Moonchild%20Productions/Pale%20Moon/Profiles/xx4f1xoz.default/extensions/jsprintsetup@edabg.com.xpi!/components/jsPrintSetup.js :: <TOP_LEVEL> :: line 1502
inner:null
data:null

Help greatly appreciated.

**Comment by mitkola** [comment]
Hi,
I suppose that there is another print operation in progress, while calling jsPrintSetup.print.
Can you provide simple page which reproduce your code and the problem?
