### ISSUE TITLE
NS_ERROR_MALFORMED_URI

### ISSUE THREAD

**Issue by uziel200** [edabg/jsprintsetup#23]
When you config a host with a port diferent that 80 or 443, the Plugin send this error:

Error:
message:Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService.newURI]
result:2152398858
name:NS_ERROR_MALFORMED_URI
filename:jar:file:///C:/Users/Sergio-Uziel/AppData/Roaming/Mozilla/Firefox/Profiles/kp0tyzoj.default/extensions/jsprintsetup@edabg.com.xpi!/components/jsPrintSetup.js
lineNumber:422
columnNumber:0
data:null

**Comment by mitkola** [comment]
Can you send an sample source code that reproduce the problem?
What is actual URI which is opened?

**Comment by uziel200** [comment]
With a simple

`var perm = jsPrintSetup.getPermissions();
`

If the current config is: "Prompt for access if site is not in Allowed/Blocked list" i get that error the URL is https://mx.test3i.net:7443/

**Comment by mitkola** [comment]
I have [fixed](https://github.com/edabg/jsprintsetup/commit/da1b023c30cce4fd6b926ccee5854cc54259f01c) this bug and now published as new version to [AMO](https://addons.mozilla.org/bg/firefox/addon/js-print-setup/versions/0.9.5.5) and waiting to be reviewed.

**Comment by uziel200** [comment]
Thank you for the reply, it was a very quick response, but I downloaded  the new version and now I get another error.

I don't open a new issue because I believe it a relative error

Error:Unsupported scheme: about

**Comment by mitkola** [comment]
jsPrintSetup don't know how to interpret internal scheme about:(by security reasons).
file: scheme is local file
http: and https: are URLs to internet hosts wich are controlled by permission manager.
Try to find workaround not to use about: scheme

**Comment by dieguitoqueiroz** [comment]
Hi, @uziel200 ...How did you solve that question. I´m with this problem, executing an page on localhost, trying to print a PDF with jsprintsetup.

**Comment by uziel200** [comment]
@dieguitoqueiroz update the plugin and then check that localhost can use the plugin as a allocated domain:

![captura de pantalla 2016-12-16 a la s 18 16 52](https://cloud.githubusercontent.com/assets/5307189/21282550/daa1454a-c3bb-11e6-8c0c-3ab6486a8bb0.png)

**Comment by dieguitoqueiroz** [comment]
Thanks @uziel200. That works!
