### ISSUE TITLE
JsPrint margin and scaling issue

### ISSUE THREAD

**Issue by surabhiv** [edabg/jsprintsetup#29]
Hello,
  I have used js print for printing customization.It works well for orientation but my code not working for margin.I have set all margins zero and also set browser's  margin zero,still it takes default margins.Please give me any solution for it.Here is code for A5 landscape.

<html>
 <head>
  <title>Printing</title>
  <style>
  *{ box-sizing:border-box;}
  body 
  {
  	font-family:verdana,arial;
  	font-size:10pt;
  	background:white;
  	} 

  div
  {
  	width:100%;border:3px solid black;
  	padding:3px;
  }
 
  </style>
  <script type="text/javascript">
  function print_ex()
  {
  	
		jsPrintSetup.setOption('orientation',jsPrintSetup.kLandscapeOrientation);
		// set top margins in millimeters

		jsPrintSetup.definePaperSize(101,101, "Custom", "Custom_Paper", "Custom PAPER",148,210,jsPrintSetup.kPaperSizeMillimeters);
		jsPrintSetup.setPaperSizeData(101);
		//jsPrintSetup.setOption('paperData',11);
		
		
		jsPrintSetup.setOption('marginTop',0);
		jsPrintSetup.setOption('marginBottom',0);
		jsPrintSetup.setOption('marginLeft',0);
		jsPrintSetup.setOption('marginRight',0);

		jsPrintSetup.setOption('unwriteableMarginTop',0);
		jsPrintSetup.setOption('unwriteableMarginLeft',0);
		jsPrintSetup.setOption('unwriteableMarginBottom',0);
		jsPrintSetup.setOption('unwriteableMarginRight',0);

		
		// set page header
		jsPrintSetup.setOption('headerStrLeft','My custom header');
		jsPrintSetup.setOption('headerStrCenter', '');
		jsPrintSetup.setOption('headerStrRight', '&PT');
		// set empty page footer
		// jsPrintSetup.setOption('footerStrLeft', '');
		// jsPrintSetup.setOption('footerStrCenter', '');
		// jsPrintSetup.setOption('footerStrRight', '');
		// Suppress print dialog
		jsPrintSetup.setSilentPrint(true);/** Set silent printing */
		jsPrintSetup.saveOptions(true);
		// Do Print
		jsPrintSetup.print();
		// Restore print dialog
		jsPrintSetup.setSilentPrint(false); /** Set silent printing back to false */

		alert("test data1");
 
  }
 </script>	 
 </head>
 <body>
 <center>
 <div>
 Print Example ...<br/>
 This is example1<br/>
 This is example2<br/>
 This is example3<br/>
 This is example4<br/>
 <br/><br/>
 
 </div>
 
 <input type="button" value="Print Now" onClick="print_ex();"/>
 </center>
 </body>
 </html>

**Comment by mitkola** [comment]
If you are using standard paper sizes (in jsPrintSetup), the recommended way is to use them. For example for iso A5 this is paper id 11.(https://github.com/edabg/jsprintsetup/wiki#enhanced-paper-data-handling)
I have attached an example which print without any margins.
```html
<html>
  <head>
	<title>Printing</title> 
<style> 
* {
	box-sizing:border-box;
} 
body {
	font-family:verdana,arial; 
	font-size:10pt; 
	background:white;
	margin: 0px; 
}
div {
	width:100%;border:3px solid black;
	padding:3px;
}
</style> <script type="text/javascript"> 
function print_ex() {

	jsPrintSetup.setGlobalOption('DEBUG', true);
	jsPrintSetup.setPrinter('PDFCreator');

	jsPrintSetup.setPaperSizeData(11); // iso_a5
	jsPrintSetup.setOption('orientation',jsPrintSetup.kLandscapeOrientation);

	// unwriteable margins
	jsPrintSetup.setOption('unwriteableMarginTop',0);
	jsPrintSetup.setOption('unwriteableMarginLeft',0);
	jsPrintSetup.setOption('unwriteableMarginBottom',0);
	jsPrintSetup.setOption('unwriteableMarginRight',0);
	// The edge measurements define the positioning of the headers and footers on the page. 
	// They're measured as an offset from the "unwriteable margin".
	jsPrintSetup.setOption('edgeTop',0);
	jsPrintSetup.setOption('edgeBottom',0);
	jsPrintSetup.setOption('edgeLeft',0);
	jsPrintSetup.setOption('edgeRight',0);
	
	// set top margins in millimeters
	jsPrintSetup.setOption('marginTop',0);
	jsPrintSetup.setOption('marginBottom',0);
	jsPrintSetup.setOption('marginLeft',0);
	jsPrintSetup.setOption('marginRight',0);

	// set empty page header
	jsPrintSetup.setOption('headerStrLeft','');
	jsPrintSetup.setOption('headerStrCenter', '');
	jsPrintSetup.setOption('headerStrRight', '');
	// set empty page footer
	jsPrintSetup.setOption('footerStrLeft', '');
	jsPrintSetup.setOption('footerStrCenter', '');
	jsPrintSetup.setOption('footerStrRight', '');
	
	// Suppress print dialog
	jsPrintSetup.clearSilentPrint();
	jsPrintSetup.setSilentPrint(true);/** Set silent printing */
	// Do Print
	jsPrintSetup.print();
	// Restore print dialog
	jsPrintSetup.setSilentPrint(false); /** Set silent printing back to false */
}
</script>
  </head>
  <body onClick="print_ex()" style="border: 1px solid black;">
Print Example ...<br />
This is example1<br />
This is example2<br />
This is example3<br />
This is example4<br />
  </body>
</html>
```

**Comment by surabhiv** [comment]
Hello,
Thanks for answer. I have tried your code.But getting below error:-
//**Error Message**
Error:
message:Component returned failure code: 0x80480002 (NS_ERROR_GFX_PRINTER_NAME_NOT_FOUND) [nsIWebBrowserPrint.print]
result:2152202242
name:NS_ERROR_GFX_PRINTER_NAME_NOT_FOUND
filename:jar:file:///C:/Users/Administrator/AppData/Roaming/Mozilla/Firefox/Profiles/c141afol.default/extensions/jsprintsetup@edabg.com.xpi!/components/jsPrintSetup.js
lineNumber:1557
columnNumber:0
data:null
stack:jsPrintSetup.prototype.print@jar:file:///C:/Users/Administrator/AppData/Roaming/Mozilla/Firefox/Profiles/c141afol.default/extensions/jsprintsetup@edabg.com.xpi!/components/jsPrintSetup.js:1557:4
print_ex@file:///C:/wamp/www/print_js/gitdemo.html:58:2
onclick@file:///C:/wamp/www/print_js/gitdemo.html:1:1

location:JS frame :: jar:file:///C:/Users/Administrator/AppData/Roaming/Mozilla/Firefox/Profiles/c141afol.default/extensions/jsprintsetup@edabg.com.xpi!/components/jsPrintSetup.js :: jsPrintSetup.prototype.print :: line 1557
//**Error message**
after this error ,I get printer selection error so I change printer name in setPrinter().It works but I still get margin as previous.

**Comment by mitkola** [comment]
In the example I'm using printer with name `PDFCreator`.
Comment the line with selecting printer.
```javascript
jsPrintSetup.setPrinter('PDFCreator');
```

**Comment by surabhiv** [comment]
sorry ,Still not getting desire output...

**Comment by mitkola** [comment]
On which platform are you testing?
Can you submit full source of your code html+js?

**Comment by surabhiv** [comment]
I have attached the print preview which i am getting by this code
![print_image](https://cloud.githubusercontent.com/assets/24150492/20669140/84e13196-b598-11e6-80b8-fd7fe03f5785.jpg)

**Comment by mitkola** [comment]
Print preview doesn't get your parameters from jsPrintSetup.
Try to print to some kind of PDF or PS printer.
On which platform are you testing?
Which is brand/model of your printer?

**Comment by surabhiv** [comment]
I am working on mozilla 50.0 (Windows operating system) and using printer HP Deskjet

**Comment by mitkola** [comment]
Can you manually setup FF to print as you desired?
Try to print on PDF or PS printer for testing.

**Comment by surabhiv** [comment]
Can you please elaborate FF...??

**Comment by mitkola** [comment]
FireFox

**Comment by surabhiv** [comment]
No,I cannot setup manually because ,i want to do it by javascript that's why i have used this addon.

**Comment by mitkola** [comment]
I know that you want to print via javascript. My question was. If you do manual print whats happen?
Are margins and orientation correct?

**Comment by surabhiv** [comment]
okk...I will check it.

**Comment by surabhiv** [comment]
Hello,
  Thanks,I got solution for this problem,actually my printer does not support this size,so i create a custom page for this printer and it works .still margin right issue remain the same for all paper sizes.

**Comment by mitkola** [comment]
If you was defined custom paper you must use [jsPrintSetup.definePaperSize](https://github.com/edabg/jsprintsetup/wiki#definepapersize) with correct settings for your paper. It is very important to use correct paperData value (for Windows) and paperName for Linux.
To find correct value for paperData under Windows you can do manual print on this paper form and then check in about:config value of setting `print.printer_your_printer.print_paper_data`.

**Comment by surabhiv** [comment]
Yes,I have used  **jsPrintSetup.definePaperSize** for custom page.

**Comment by mitkola** [comment]
What are parameters of your custom paper size?
What is value of `paper_data` and how you determined?

**Comment by surabhiv** [comment]
Solved...Thank you.
