### ISSUE TITLE
Star Tsp100 futureprnt or Epson TM T88v receipt printers

### ISSUE THREAD

**Issue by monicae** [edabg/jsprintsetup#3]
Good morning:
Headers and footers still printing on the receipts but the same page works fine on a laser printer  also the receipts are not cutting in the correct position. Any ideas?

**Comment by mitkola** [comment]
Hi,
Firefox store print settings for each printer separately.
Possible reasons for printing with different settings on different printers can be:
- using windows.print instead jsPrintSetup.print (which use stored settings for printer)
- show print dialog (which reads stored settings for printer) 
  To prevent this you can do the following:
- set margins, header and footer
- select silent printing
- call jsPrintSetup.print.
  (For more information you can see examples in reference)
  If your problem persist, you can paste code snippet to see what exactly happened.

**Comment by monicae** [comment]
Thank you for your response:
This is the code we use:

printIt: function(html, head, body, prtr, copies) {
    // add js print code
    var scrpt = '';
        scrpt += '<script>';
        scrpt += "jsPrintSetup.setOption('headerStrLeft', '');";
        scrpt += "jsPrintSetup.setOption('headerStrCenter', '');";
        scrpt += "jsPrintSetup.setOption('headerStrRight', '');";
        scrpt += "jsPrintSetup.setOption('footerStrLeft', '');";
        scrpt += "jsPrintSetup.setOption('footerStrCenter', '');";
        scrpt += "jsPrintSetup.setOption('footerStrRight', '');";
        scrpt += "jsPrintSetup.setOption('marginLeft', 0);";
        scrpt += "jsPrintSetup.setOption('marginRight', 0);";
        scrpt += "jsPrintSetup.setOption('orientation', jsPrintSetup.kPortraitOrientation);";
        scrpt += 'jsPrintSetup.setSilentPrint(true);';
        scrpt += "jsPrintSetup.setOption('numCopies'," + copies + ");";
        scrpt += "jsPrintSetup.setOption('outputFormat', jsPrintSetup.kOutputFormatNative);";

```
    if (prtr) {
      prtr = prtr.replace(/\\/g,"\\\\");    // network printer fix.
  scrpt += 'jsPrintSetup.setPrinter("' + prtr + '");';
}

scrpt += 'setTimeout(function(){jsPrintSetup.printWindow(window);}, 3000)';
scrpt += '<' + '/script>';

// build doc
if (html) {
  var x = html.indexOf('</body');
  var doc = html.substr(0,x) + scrpt + html.substr(x);
}
else {
  var doc = '';
    doc += '<!DOCTYPE html>';
      doc += '<html lang=en>';
      doc += '<head>';
      doc += head;
      doc += '</head>';
      doc += '<body>';
    doc += body;
      doc += scrpt;
      doc += '</body>';
      doc += '</html>';
    }

var docx = 'data:text/html;charset=utf-8,' + encodeURIComponent(doc);
var ifr = document.createElement('iframe');

ifr.id = 'printFrame';
ifr.src = docx;
$(ifr).css('display', 'none');
document.body.appendChild(ifr);

setTimeout(function(){    // put silent print back to false
  jsPrintSetup.setSilentPrint(false);
},5000);
```

  },

**Comment by mitkola** [comment]
The source is unreadable.

**Comment by monicae** [comment]
the code we use, :

printIt: function(html, head, body, prtr, copies) {
    // add js print code
    var scrpt = '';
        scrpt += '<script>';
        scrpt += "jsPrintSetup.setOption('headerStrLeft', '');";
        scrpt += "jsPrintSetup.setOption('headerStrCenter', '');";
        scrpt += "jsPrintSetup.setOption('headerStrRight', '');";
        scrpt += "jsPrintSetup.setOption('footerStrLeft', '');";
        scrpt += "jsPrintSetup.setOption('footerStrCenter', '');";
        scrpt += "jsPrintSetup.setOption('footerStrRight', '');";
        scrpt += "jsPrintSetup.setOption('marginLeft', 0);";
        scrpt += "jsPrintSetup.setOption('marginRight', 0);";
        scrpt += "jsPrintSetup.setOption('orientation', jsPrintSetup.kPortraitOrientation);";
        scrpt += 'jsPrintSetup.setSilentPrint(true);';
        scrpt += "jsPrintSetup.setOption('numCopies'," + copies + ");";
        scrpt += "jsPrintSetup.setOption('outputFormat', jsPrintSetup.kOutputFormatNative);";

        if (prtr) {
          prtr = prtr.replace(/\\/g,"\\\\");    // network printer fix.
      scrpt += 'jsPrintSetup.setPrinter("' + prtr + '");';
    }

    scrpt += 'setTimeout(function(){jsPrintSetup.printWindow(window);}, 3000)';
    scrpt += '<' + '/script>';

    // build doc
    if (html) {
      var x = html.indexOf('</body');
      var doc = html.substr(0,x) + scrpt + html.substr(x);
    }
    else {
      var doc = '';
        doc += '<!DOCTYPE html>';
          doc += '<html lang=en>';
          doc += '<head>';
          doc += head;
          doc += '</head>';
          doc += '<body>';
        doc += body;
          doc += scrpt;
          doc += '</body>';
          doc += '</html>';
        }

    var docx = 'data:text/html;charset=utf-8,' + encodeURIComponent(doc);
    var ifr = document.createElement('iframe');

    ifr.id = 'printFrame';
    ifr.src = docx;
    $(ifr).css('display', 'none');
    document.body.appendChild(ifr);

    setTimeout(function(){    // put silent print back to false
      jsPrintSetup.setSilentPrint(false);
    },5000);
  },

**Comment by monicae** [comment]
the code we use, you can cut/paste this:

printIt: function(html, head, body, prtr, copies) {
    // add js print code
    var scrpt = '';
        scrpt += '<script>';
        scrpt += "jsPrintSetup.setOption('headerStrLeft', '');";
        scrpt += "jsPrintSetup.setOption('headerStrCenter', '');";
        scrpt += "jsPrintSetup.setOption('headerStrRight', '');";
        scrpt += "jsPrintSetup.setOption('footerStrLeft', '');";
        scrpt += "jsPrintSetup.setOption('footerStrCenter', '');";
        scrpt += "jsPrintSetup.setOption('footerStrRight', '');";
        scrpt += "jsPrintSetup.setOption('marginLeft', 0);";
        scrpt += "jsPrintSetup.setOption('marginRight', 0);";
        scrpt += "jsPrintSetup.setOption('orientation', jsPrintSetup.kPortraitOrientation);";
        scrpt += 'jsPrintSetup.setSilentPrint(true);';
        scrpt += "jsPrintSetup.setOption('numCopies'," + copies + ");";
        scrpt += "jsPrintSetup.setOption('outputFormat', jsPrintSetup.kOutputFormatNative);";

        if (prtr) {
          prtr = prtr.replace(/\\/g,"\\\\");    // network printer fix.
      scrpt += 'jsPrintSetup.setPrinter("' + prtr + '");';
    }

    scrpt += 'setTimeout(function(){jsPrintSetup.printWindow(window);}, 3000)';
    scrpt += '<' + '/script>';

    // build doc
    if (html) {
      var x = html.indexOf('</body');
      var doc = html.substr(0,x) + scrpt + html.substr(x);
    }
    else {
      var doc = '';
        doc += '<!DOCTYPE html>';
          doc += '<html lang=en>';
          doc += '<head>';
          doc += head;
          doc += '</head>';
          doc += '<body>';
        doc += body;
          doc += scrpt;
          doc += '</body>';
          doc += '</html>';
        }

    var docx = 'data:text/html;charset=utf-8,' + encodeURIComponent(doc);
    var ifr = document.createElement('iframe');

    ifr.id = 'printFrame';
    ifr.src = docx;
    $(ifr).css('display', 'none');
    document.body.appendChild(ifr);

    setTimeout(function(){    // put silent print back to false
      jsPrintSetup.setSilentPrint(false);
    },5000);
  },

**Comment by monicae** [comment]
the code we use, :
printIt: function(html, head, body, prtr, copies) {
    // add js print code
    var scrpt = '';
        scrpt += '<script>';
        scrpt += "jsPrintSetup.setOption('headerStrLeft', '');";
        scrpt += "jsPrintSetup.setOption('headerStrCenter', '');";
        scrpt += "jsPrintSetup.setOption('headerStrRight', '');";
        scrpt += "jsPrintSetup.setOption('footerStrLeft', '');";
        scrpt += "jsPrintSetup.setOption('footerStrCenter', '');";
        scrpt += "jsPrintSetup.setOption('footerStrRight', '');";
        scrpt += "jsPrintSetup.setOption('marginLeft', 0);";
        scrpt += "jsPrintSetup.setOption('marginRight', 0);";
        scrpt += "jsPrintSetup.setOption('orientation', jsPrintSetup.kPortraitOrientation);";
        scrpt += 'jsPrintSetup.setSilentPrint(true);';
        scrpt += "jsPrintSetup.setOption('numCopies'," + copies + ");";
        scrpt += "jsPrintSetup.setOption('outputFormat', jsPrintSetup.kOutputFormatNative);";
        if (prtr) {
          prtr = prtr.replace(/\\/g,"\\\\");    // network printer fix.
      scrpt += 'jsPrintSetup.setPrinter("' + prtr + '");';
    }
    scrpt += 'setTimeout(function(){jsPrintSetup.printWindow(window);}, 3000)';
    scrpt += '<' + '/script>';
    // build doc
    if (html) {
      var x = html.indexOf('</body');
      var doc = html.substr(0,x) + scrpt + html.substr(x);
    }
    else {
      var doc = '';
        doc += '<!DOCTYPE html>';
          doc += '<html lang=en>';
          doc += '<head>';
          doc += head;
          doc += '</head>';
          doc += '<body>';
        doc += body;
          doc += scrpt;
          doc += '</body>';
          doc += '</html>';
        }
    var docx = 'data:text/html;charset=utf-8,' + encodeURIComponent(doc);
    var ifr = document.createElement('iframe');
    ifr.id = 'printFrame';
    ifr.src = docx;
    $(ifr).css('display', 'none');
    document.body.appendChild(ifr);
    setTimeout(function(){    // put silent print back to false
      jsPrintSetup.setSilentPrint(false);
    },5000);
  },

[the code we use.docx](https://github.com/edabg/jsprintsetup/files/68537/the.code.we.use.docx)

**Comment by monicae** [comment]
[the code we use.docx](https://github.com/edabg/jsprintsetup/files/68541/the.code.we.use.docx)

**Comment by mitkola** [comment]
You must call `jsPrintSetup.setPrinter` before modify settings.
Also I recommend to call `jsPrintSetup.clearSilentPrint()` beafore jsPrintSetup.setSilentPrint(true) to be shure that stored setting for silent printer doesn't matter.
And something other is that you can call `jsPrintSetup.setSilentPrint(false)` after `jsPrintSetup.printWindow(window)`.

``` javascript
printIt: function(html, head, body, prtr, copies) {
    // add js print code
    var scrpt = '';
        scrpt += '<script>';
        if (prtr) {
            prtr = prtr.replace(/\\/g,"\\\\");    // network printer fix.
            scrpt += 'jsPrintSetup.setPrinter("' + prtr + '");';
        }
        scrpt += "jsPrintSetup.setOption('headerStrLeft', '');";
        scrpt += "jsPrintSetup.setOption('headerStrCenter', '');";
        scrpt += "jsPrintSetup.setOption('headerStrRight', '');";
        scrpt += "jsPrintSetup.setOption('footerStrLeft', '');";
        scrpt += "jsPrintSetup.setOption('footerStrCenter', '');";
        scrpt += "jsPrintSetup.setOption('footerStrRight', '');";
        scrpt += "jsPrintSetup.setOption('marginLeft', 0);";
        scrpt += "jsPrintSetup.setOption('marginRight', 0);";
        scrpt += "jsPrintSetup.setOption('orientation', jsPrintSetup.kPortraitOrientation);";
        scrpt += 'jsPrintSetup.clearSilentPrint();'; // clear default saved setting
        scrpt += 'jsPrintSetup.setSilentPrint(true);';
        scrpt += "jsPrintSetup.setOption('numCopies'," + copies + ");";
        scrpt += "jsPrintSetup.setOption('outputFormat', jsPrintSetup.kOutputFormatNative);";
// moved above before set settings
//        if (prtr) {
//          prtr = prtr.replace(/\\/g,"\\\\");    // network printer fix.
//          scrpt += 'jsPrintSetup.setPrinter("' + prtr + '");'; 
//        }

    scrpt += 'setTimeout(function(){jsPrintSetup.printWindow(window);}, 3000)';
    scrpt += '<' + '/script>';

    // build doc
    if (html) {
      var x = html.indexOf('</body');
      var doc = html.substr(0,x) + scrpt + html.substr(x);
    }
    else {
      var doc = '';
        doc += '<!DOCTYPE html>';
          doc += '<html lang=en>';
          doc += '<head>';
          doc += head;
          doc += '</head>';
          doc += '<body>';
        doc += body;
          doc += scrpt;
          doc += '</body>';
          doc += '</html>';
        }

    var docx = 'data:text/html;charset=utf-8,' + encodeURIComponent(doc);
    var ifr = document.createElement('iframe');

    ifr.id = 'printFrame';
    ifr.src = docx;
    $(ifr).css('display', 'none');
    document.body.appendChild(ifr);

    setTimeout(function(){    // put silent print back to false
      jsPrintSetup.setSilentPrint(false);
    },5000);
  },
```

**Comment by monicae** [comment]
Thank you very much!!
This did the work. My Epson and the start are all set now.

Monica

-----Original Message-----
