### ISSUE TITLE
jsPrintSetup is not working on mac os x

### ISSUE THREAD

**Issue by ishehata** [edabg/jsprintsetup#34]
I was trying to get jsPrintSetup to work on my laptop (macbook Pro), and i have latest stable version of Firefox.

I installed the jsprintsetup addon, restarted firefox (many times),
but when i try to access jsPrintSetup from the console, it says it is undefined, 
i have tried the plugin on a virtual machine that have ubuntu installed and it worked fine,
so i assume the problem only happens on mac os x.

**Comment by mitkola** [comment]
Try to write simple HTML with `javascript` to test it

**Comment by ishehata** [comment]
ok i tried it now, didn't work either, this error showed up in the console:

```
ReferenceError: jsPrintSetup
```

and here is my html code

```html
<html>
<body>
    <h4>Hello World</h4>
    <script type="text/javascript">
        jsPrintSetup.print();
    </script>
</body>
</html>
```

and by the way, i have tried my original code on linux, it works fine.

**Comment by ishehata** [comment]
i have found something weird,

when i go to firefox's addons page "from the browser menu" and open console, i can use jsPrintSetup, but in any webpage the console just reports that jsPrintSetup is undefined.

**Comment by mitkola** [comment]
Do you have some other add-ons  which can block jsPrintSetup?
I have tested on Mac OS Yosemite 10.10 following example and works.
```html
<html>
<head>
   <meta charset="utf-8">
</head>
<body>
    <h4>Hello World</h4>
    <script type="text/javascript">
        alert(jsPrintSetup);
    </script>
</body>
</html>
```
Produce following:
![image](https://cloud.githubusercontent.com/assets/11041032/22055081/e5e099e6-dd61-11e6-9a35-d4e46a3c0619.png)

**Comment by ishehata** [comment]
i have only other two extension, 
 - Json Formatter
 - ForerunnerDB

i don't think any of those would block jsPrintSetup, is there is a way to debug this and see what's going on ?

**Comment by mitkola** [comment]
Are you sure that add-on is installed correctly?
What is displayed in list of installed add-ons?

**Comment by ishehata** [comment]
so i did a clean install with only jsPrintSetup installed and it works just fine, i have no clue why it didn't work before, maybe another plugin caused this behaviour, thanks anyway.
