### ISSUE TITLE
html title problem

### ISSUE THREAD

**Issue by moryekram** [edabg/jsprintsetup#43]
Hello.
I have html file that has utf-8 title. when i print using jsPrintSetup title is not valid.
title should be "نامه شماره ۴۵۴/11"
Please help me.Thanks.
[u21124iy.txt](https://github.com/edabg/jsprintsetup/files/1040561/u21124iy.txt)

**Comment by mitkola** [comment]
First try to manual print this content.
`jsPrintSetup` doesn't modify title.
I see that  `window.close()` is called immediately after `jsPrintSetup.printWindow(window)`.
jsPrintSetup.printWindow(window) is executed asynchronously. This mean that execution of script continue after calling of method jsPrintSetup.printWindow(window) while printing may be in progress which can result in problems.
The simplest way to workaroud is to call `window.close()` after timeout.

**Comment by moryekram** [comment]
Because "/" is not valid in file name in windows I remove it from my code and print it manually.my MicrosoftPrintToPDF printer change title to file path.But with jsPrintSetup title is not correct.please check this file.
[u21124iy.txt](https://github.com/edabg/jsprintsetup/files/1040835/u21124iy.txt)
Thanks

**Comment by mitkola** [comment]
`jsPrintSetup` doesn't modify title implicitly. Only when you use  `jsPrintSetup.setOption('title', 'Some title')`.
You can try following:
- print directly to printer (not set option toFileName)
- try to set title via `jsPrintSetup.setOption('title', 'Some title')`

btw. Can you post not minified code.

**Comment by moryekram** [comment]
Hello again.I try your suggestion but title is incorrect.
here this is my file
[ob02auns.txt](https://github.com/edabg/jsprintsetup/files/1057054/ob02auns.txt)

**Comment by mitkola** [comment]
I have made some corrections to your example.
- Fixed margins
- modified `headerStrCenter` for testing
For me this example is working.

[test.html.txt](https://github.com/edabg/jsprintsetup/files/1057815/test.html.txt)

**Comment by moryekram** [comment]
this is result for me.
![0101](https://user-images.githubusercontent.com/18113847/27021407-53f8c710-4f5d-11e7-8b93-d57101c9b67f.PNG)
![0202](https://user-images.githubusercontent.com/18113847/27021412-57c60948-4f5d-11e7-8575-333ecce128cd.PNG)

**Comment by mitkola** [comment]
I think that this is problem of 'Microsoft Print To PDF' driver.
I have tested with ['PDF Creator'](http://www.pdfforge.org/pdfcreator) and title is displayed correct.
![image](https://user-images.githubusercontent.com/11041032/27021909-08ae66f6-4f54-11e7-8050-a4cf38ea0735.png)

**Comment by moryekram** [comment]
OK,thanks.I test it.
